Python/Django/IOT/devices/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name="index"),
    # 显示所有主题
    url(r'^topics/$', views.topics, name='topics'),
    # 显示特定主题的详细页面
    url(r"^topic/(?P<topic_id>\d+)/$", views.topic, name='topic'),
    # 用于添加新主题的页面
    url(r'^add_topic/$', views.add_topic, name="add_topic"),
    # 用于添加新的条目,其中topic_id是匹配的Topic ID
    url(r'^add_entry/(?P<topic_id>\d+)/$', views.add_entry, name="add_entry"),
    # 条目编辑
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name="edit_entry"),
]

Python/Django/IOT/monitor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(("devices.urls", "devices"), namespace="devices")),
    path(r'users/', include(("users.urls", "users"), namespace="users")),
]

Python/Django/IOT/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

app_name = "users"
urlpatterns = [
    # 登录页面
    url(r"^login/$", LoginView.as_view(template_name="users/login.html"), name='login'),
    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),
    # 注册
    url(r'^register/$', views.register, name="register"),
]

Python/Django/IOT/devices/models.py
from django.db import models
from django.contrib.auth.models import User

'''
https://docs.djangoproject.com/en/3.0/ref/models/fields/
'''
class Topic(models.Model):
    name = models.CharField(max_length=32)
    deviceId = models.CharField(max_length=16)
    date_added = models.DateTimeField(auto_now_add=True)
    # 建立和User的外键关系，实现将数据关联到用户
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        # 模型的字符串表示
        return self.name + self.deviceId

class Entry(models.Model):
    # 外键
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, default="")
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        '''
            存储管理模型的额外信息
        '''
        verbose_name_plural = 'entries'

    def __str__(self):
        # 设置显示条目的信息
        return self.description[0:32] + "..."

Python/Django/IOT/users/models.py
from django.db import models

# Create your models here.

Python/Django/IOT/devices/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    # 内嵌Meta类，确定根据哪个模型创建表单以及表单中包含哪些字段
    class Meta:
        model = Topic
        fields = ["name", "deviceId"]
        lables = {
            "name"      :   "",
            "devicesId" :   ""
        }

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["description"]
        labels = {
            "description"   :   ""
        }
        widgets = {
            "description" : forms.Textarea(attrs={'cols' : 80})
        }

Python/Django/IOT/devices/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# 创建视图
def index(request):
    return render(request, "devices/index.html")

# 只允许已登录的用户请求该页面
@login_required         # 检查用户是否登录，只有登录才会执行下方的代码
def topics(request):
    '''
    导入数据相关联模型
    :param request: 用户请求
        user        保存了用户的相关信息
    :return:
    '''
    # 导入数据相关联模型,通过filter只允许用户访问自己的主题
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    # 定义将要发送给模板的上下文
    context = {'topics' : topics}
    return render(request, 'devices/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    # 确认请求主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by("-date_added")
    context = {
        "topic"     : topic,
        "entries"   : entries
    }
    return render(request, "devices/topic.html", context)

@login_required
def add_topic(request):
    '''
    添加新主题
    :param request:
    :return:
    '''
    if request.method != "POST":
        # 未提交数据，创建一个新的表单
        form = TopicForm()
    else:
        # POST提交数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            # 添加主题时，将主题关联到当前用户
            new_topic.owner = request.user
            new_topic.save()
            # 用户提交数据后将其重定向到topics网页，其中reverse根据指定的URL模型确定URL
            return HttpResponseRedirect(reverse("devices:topics"))
    context = {'form' : form }
    return render(request, "devices/add_topic.html", context)

@login_required
def add_entry(request, topic_id):
    '''
    添加新的条目
    :param request:
    :return:
    '''
    topic = Topic.objects.get(id=topic_id)
    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            # commit=False使得Django创建一个Entry对象,并将其存储于new_entry，但不保存到数据库
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            # 将数据保存到数据库，并将其和正确的Topic关联
            new_entry.save()
            return HttpResponseRedirect(reverse("devices:topic", args=[topic_id]))
    context = {
        "topic"     :   topic,
        "form"      :   form
    }
    return render(request, "devices/add_entry.html", context)

@login_required
def edit_entry(request, entry_id):
    '''
    编辑即有条目
    :param request:
    :param entry_id:
    :return:
    '''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != "POST":
        # 初次请求，使用当前条目的内容填充表单
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("devices:topic", args=[topic.id]))
    context = {
        'entry'     :   entry,
        'topic'     :   topic,
        'form'      :   form
    }
    return render(request, "devices/edit_entry.html", context)

Python/Django/IOT/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, login, authenticate

def logout_view(request):
    '''
    注销用户
    :param request:
    :return:
    '''
    logout(request)
    return HttpResponseRedirect(reverse("devices:index"))

def register(request):
    '''
    注册新用户
    :param request:
    :return:
    '''
    if request.method != "POST":
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填好的表单
        form = UserCreationForm(data=request.POST)
        # 检查数据是否有效：用户名是否包含非法字符;输入两个密码相同;用户无试图做恶意的事项
        if form.is_valid():
            # 将用户名和密码的散列值保存至数据库
            new_user = form.save()
            # 让用户自动登录，再重新定向到主页
            authenticate_user = authenticate(username=new_user.username, \
                password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse("devices:index"))
    context = {'form': form}
    return render(request, "users/register.html", context)

Python/Django/IOT/devices/templates/devices/add_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Entry</title>
</head>
<body>
    {% extends 'devices/base.html' %}

    {% block content %}
    <p><a href="{% url 'devices:topic' topic.id %}">{{topic}}</a></p>
    <p> Add a new Entry:</p>
    <form action="{% url 'devices:add_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Add Entry</button>
    </form>
    {% endblock content %}
</body>
</html>

Python/Django/IOT/devices/templates/devices/add_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Topic</title>
</head>
<body>
    {% extends 'devices/base.html' %}
    {% load bootstrap3 %}

    {% block header%}
        <h2>Add a new topic:</h2>
    {% endblock header%}

    {% block content %}
        <form action="{% url 'devices:add_topic' %}" method="post">
            <!-- 防止攻击者利用表单来获得对服务器未经授权的访问，即跨站请求伪造 -->
            {% csrf_token %}
            <!-- 自动创建显示表单所需要的全部字段
                 as_p使得以段落格式渲染所有的表单元素，是整洁显示表单的最简单的方式-->
            <!--{{ form.as_p }}-->
            {% bootstrap_form form %}
            {% buttons %}
                <button class="btn btn-primary" name="submit">Add Topic</button>
            {% endbuttons %}
        </form>
    {% endblock content %}
</body>
</html>

Python/Django/IOT/devices/templates/devices/base.html
<!DOCTYPE html>
<!-- 加载django-bootstrap3模板 https://getbootstrap.com/docs/4.4/examples/-->
{% load bootstrap3 %}
<html lang="en">
<head>
    <!-- 将正确显示页面所需要的信息告诉浏览器 -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- 设置标题栏显示的内容 -->
    <title>Title</title>

    <!-- django-bootstrap3自定义模板标签，它将Django包含所有的Bootstrap样式文件-->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <!-- Static Navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <!-- 定义一个按钮在窗口太窄无法显示整个导航栏时显示出来 -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                </button>

                <!-- 在导航的最左边显示项目名称，将其设置为主页的链接-->
                <a class="navbar-brand" href="{% url 'devices:index' %}">Devices</a>
            </div>
        </div>

        <!-- 网站导航链接 -->
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'devices:index' %}">Devices</a></li>
                <li><a href="{% url 'devices:topics' %}">Topics</a></li>
                <li><a href="{% url 'devices:add_topic' %}">Add a new topic</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>Hello, {{ user.username }}.</li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">Login</a></li>
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div><!-- /.nav-collapse -->
    </nav>
    <div>
        <div class="container">
            <div class="page-header">
                {% block header %} {% endblock header %}
            </div>
            <div>
                <!-- content占位符，包含的信息由子模板决定 -->
                {% block content %} {% endblock content %}
            </div>
        </div>
    </div><!-- /container-->
    <p>
        <a href="{% url 'devices:index' %}">Footer</a>
    </p>
</body>
</html>

Python/Django/IOT/devices/templates/devices/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Entry</title>
</head>
<body>
    {% extends 'devices/base.html' %}
    {% block content %}
        <p><a href="{% url 'devices:topic' topic.id %}">{{ topic }}</a></p>
        <p>Edit Entry:</p>>
        <form method="post" action="{% url 'devices:edit_entry' entry.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Save Changes</button>
        </form>
    {% endblock content%}
</body>
</html>

Python/Django/IOT/devices/templates/devices/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Devices</title>
</head>
<body>
    {% extends "devices/base.html" %}

    <!-- 使用jumbotron设置主页的样式 -->
    {% block header%}
        <div class="jumbotron">
            <h1>尝试搭建一个IOT平台</h1>
        </div>
    {% endblock header%}
    <!-- 指定父模板 -->
    {% block content %}
        <h2>
            <a href="{% url 'users:register' %}">Register an account </a>
            , and to list the topics you created.
        </h2>
        <h2>
            List the topics, add new topic,
            and you can make an entry summarizing what you want to show.
        </h2>
    {% endblock content %}
</body>
</html>

Python/Django/IOT/devices/templates/devices/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic</title>
</head>
<body>
    {% extends 'devices/base.html' %}

    {% block header %}
        <h1>{{Topic}}</h1>
    {% endblock header %}


    {% block content %}
    <p>Entries:</p>
    <p>
        <a href="{% url 'devices:add_entry' topic.id %}">Add a new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
            <div class="panel panel-default">
                <div class="panel-heading"> <!-- 面板标题 -->
                    <h3>
                        {{entry.date_added | date:"M d, Y H:i"}}
                        <small>
                            <a href="{% url 'devices:edit_entry' entry.id %}">Edit Entry</a>
                        </small>
                    </h3>
                </div>
                <div class="panel-body"> <!-- 面板主体 -->
                    {{entry.description | linebreaks}}
                </div>
            </div><!-- panel -->
        <!--指定列表为空是如何处理-->
        {% empty %}
            There are no entries for this yet.
        {% endfor %}
    </ul>
    {% endblock content %}
</body>
</html>

Python/Django/IOT/devices/templates/devices/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
    {% extends 'devices/base.html' %}
    {% block header %}
        <h1>Topics:</h1>
    {% endblock header %}

    {% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'devices:topic' topic.id %}">{{topic}}</a>
                </h3>
            </li>
        <!--指定列表为空是如何处理-->
        {% empty %}
            <li>No Topic has been added !</li>
        {% endfor %}
    </ul>
    {% endblock content %}
</body>
</html>

Python/Django/IOT/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    {% extends "devices/base.html" %}
    {% load bootstrap3 %}

    {% block header %}
        <h2>Login in to your account.</h2>
    {% endblock header %}

    {% block content %}
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {% bootstrap_form form %} <!-- 将Bootstrap样式规则应用于各个表单元素-->

        {% buttons %}
        <button class="btn btn-primary" name="submit">Login</button>
        {% endbuttons %}
        <!-- 确定用户登录成功之后重定向到那个页面 -->
        <input type="hidden" name="next" value="{% url 'devices:index' %}"/>
    </form>
    {% endblock content %}
</body>
</html>

Python/Django/IOT/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    {% extends "devices/base.html" %}
    {% block content %}
        <form method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Resister</button>
            <input type="hidden" name="next" value="{% url 'devices:index' %}"/>
        </form>
    {% endblock content %}
</body>
</html>